# Generated by Django 4.0.4 on 2022-06-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0005_friendlist_friendrequest_subscribelist_delete_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='subscribelist',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subscribelist',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='SubscribeList',
        ),
    ]
