# Generated by Django 4.0.4 on 2022-06-08 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends_app', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='Friendship',
        ),
    ]
