# Generated by Django 4.0.4 on 2022-06-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0008_rename_friendlist_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='accepted_at',
        ),
    ]
