# Generated by Django 4.0.4 on 2022-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0009_remove_friendship_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='wait_answer',
            field=models.BooleanField(default=True),
        ),
    ]
