# Generated by Django 4.0.4 on 2022-05-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0003_rename_tag_tag_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='tag',
        ),
    ]
