# Generated by Django 4.0.4 on 2022-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0004_rename_tags_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastag', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
