# Generated by Django 4.0.4 on 2022-05-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0005_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
