# Generated by Django 4.0.4 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0006_rename_hastag_hashtag_hashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Хэштег', 'verbose_name_plural': 'Хэштеги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
