# Generated by Django 4.0.4 on 2022-05-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
