# Generated by Django 4.0.4 on 2022-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_post_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagine',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
