# Generated by Django 4.0.4 on 2022-05-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0008_post_user_alter_post_imagine_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publication_app.post'),
            preserve_default=False,
        ),
    ]
