# Generated by Django 4.0.4 on 2022-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0012_alter_post_imagine_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
