# Generated by Django 4.0.4 on 2022-05-11 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0013_alter_post_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_time',
        ),
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
    ]
