# Generated by Django 4.0.4 on 2022-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0016_imagepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagine',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='posts/%Y'),
        ),
    ]
