# Generated by Django 4.0.4 on 2022-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0017_remove_post_imagine_alter_imagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y'),
        ),
    ]
