# Generated by Django 4.0.4 on 2022-05-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0019_created_profile_for_existing_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
