# Generated by Django 4.0.4 on 2022-05-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0021_post_tag_alter_comment_text_alter_imagepost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
