# Generated by Django 4.0.4 on 2022-05-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0001_initial'),
        ('publication_app', '0022_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='tag_app.tag'),
        ),
    ]
