# Generated by Django 4.0.4 on 2022-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0002_rename_tags_tag_tag'),
        ('publication_app', '0023_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tagpost', to='tag_app.tag'),
        ),
    ]
