# Generated by Django 4.0.4 on 2022-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0005_hashtag'),
        ('publication_app', '0026_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hastag',
            field=models.ManyToManyField(to='tag_app.hashtag'),
        ),
    ]
