# Generated by Django 4.0.4 on 2022-05-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0006_rename_hastag_hashtag_hashtag'),
        ('publication_app', '0027_post_hastag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hastag',
        ),
        migrations.CreateModel(
            name='HashtagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_app.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication_app.post')),
            ],
        ),
    ]
