# Generated by Django 4.0.4 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0028_remove_post_hastag_hashtagpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'Фотография  поста', 'verbose_name_plural': 'Фотограции постов'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
