# Generated by Django 4.0.4 on 2022-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0008_alter_hashtag_hashtag_alter_tag_tag'),
        ('publication_app', '0030_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tag_app.tag'),
        ),
    ]
