# Generated by Django 4.0.4 on 2022-05-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0032_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtagpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_post', to='publication_app.post'),
        ),
    ]
