# Generated by Django 4.0.4 on 2022-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0008_alter_hashtag_hashtag_alter_tag_tag'),
        ('publication_app', '0033_alter_hashtagpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_post', to='tag_app.tag'),
        ),
    ]
