# Generated by Django 4.0.4 on 2022-05-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0036_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
