# Generated by Django 4.0.4 on 2022-05-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0038_post_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
