# Generated by Django 4.0.4 on 2022-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
