# Generated by Django 4.0.4 on 2022-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menuitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
