# Generated by Django 4.0.4 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_profile_date_of_birth_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
