# Generated by Django 4.0.4 on 2022-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
        ('publication_app', '0039_delete_like'),
        ('like_app', '0002_like_comment_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='com_like', to='comment_app.comment'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(null=True, related_name='post_like', to='publication_app.post'),
        ),
    ]
