# Generated by Django 4.0.4 on 2022-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
        ('publication_app', '0039_delete_like'),
        ('like_app', '0003_remove_like_comment_like_comment_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='com_like', to='comment_app.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like', to='publication_app.post'),
        ),
    ]
